---
title: "Annotated Bibliography"
author: "Aaron Graybill"
date: "9/27/2021"
output:
  word_document: default
  pdf_document:
biblio-style: apalike
csl: "../apa.csl"
bibliography: InUseBib.bib
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
refs <- bibtex::read.bib("InUseBib.bib")
```

## Introduction and Selection Criteria
As you will immediately notice none of these papers directly relate to the way that artists build notoriety over time. However, I have proxied artistic reputation with corporate reputation (branding) to get a better sense of how these problems can be modeled. In addition I cite, Spence (1973) because it gives an alternate approach to how artists build reputation by ex ante signalling competence instead of deciding whether or not to follow through on selling a high quality product.

### Decision-Making under Uncertainty: Capturing Dynamic Brand Choice Processes in Turbulent Consumer Goods Markets

`r capture.output(print(refs[2]))`

1. To begin, parts of this paper go over my head. However, this paper has two main purposes. 1. to develop a discrete-choice model of consumer beliefs and purchases of goods of uncertain value. 2. They get to a point where the model becomes unsolvable and pioneer an application of the empirical technique (Montecarlo Integration Simulation) to exemplify how complicated discrete choice problems with uncertainty can be tackled empirically. The paper brings together multiple relevant techniques for me, namely discrete choice under uncertainty and Bayesian updating over multiple periods.

2. The authors seem to position their work as not that new theoretically, but new in terms of estimability. Their main theoretical difference is in not forcing a relationship between periods. Reputation can update if that helps the consumer, but otherwise it may not. In terms of empirics, the authors indicate that their Montecarlo simulation technique is the first time its being applied to the marketing literature and give a proof of concept for grocery store laundry detergent data. 

3. The data used in the analysis comes from A.C. Nielsen incorporated. To my knowledge they seem to do micro-level surveys of consumer purchase patterns. In this case, the data is about the purchase of laundry detergent in Sioux Falls South Dakota and Springfield Montana. We have data about time of purhcase, brand, and some have telemeters that can trackc which TV ads they've been shown. The data is broken down by those two locations and from my understanding the South Dakota data was used as somethnig of a training dataset and the Montana data was used as the "test" data. There's no specific mention of the sample itself being representative, but the authors claim to use the detergent data because of its frequent repurchase rate, frequent advertising, and they claim that "previous research has shown detergents to be
low in variety seeking (Elrod 1988)" p. 9.

4. I'll cover the theoretical methodology then the empirical methodology.
    + Theoretical: At a high level, the method (model) takes the perspective of the consumer. In each period, the consumer can choose exactly one product to buy one unit of. Ex ante, they don't know the quality of the product, but their experiences with the product and its advertising form its perceived value. The consumers problem is to update their beliefs about the quality of each product offering while optimizing their expected consumption stream over time (using dynamic programming). An important note here is that consumer beliefs are heterogenous (or at least not constraned to be be homogenous) and that time periods are discrete.
    + Empirical: The Authors then pivot their theoretical model to an empirical one using the data given above. This bit goes well over my head, but my understanding of the general sense is that the authors try to estimate the parameters in the model by observing consumption patterns over time. The tricky bit is that Bayesian updating requires you to take multiple (potential unseperable) integrals over the reputation space of multiple products. The authors use Montecarlo integration (a buzzword I've heard of but don't fully understand) to estimate these integrals. From my Wikipediaing, I think what's happening is that the individual observations are treated as points to evaluate the integrand of the multidimensional integral which allows the authors to estimate the general shape of the total integral? But that's little more than speculation.
    
5. As I have mentioned, the authors position their main result as the first application of montecarlo integration to the discrete choice marketing literature, and they show that their "training" on the South Dakota data allows them to reasonably well predict the purchase patterns of the Montana consumers.From the theory point of view, there are no stringent assumptions made, but what the model gains in flexibility it loses in tractibility. As we will see with other papers, simpler models can have closed forms solutions, but require more assumptions.

6. The followup question I have in reading this work is related to how it can be generalized to a two-player game. This paper focuses on the consumer setting.

### The Role of Market Forces in Assuring Contractual Performance
 
`r capture.output(print(refs[3]))`

1. This is a pure theory paper discussing how firms should optimally build reputation (branding) with an exogenous impact of reputation. The paper shows that if a firm can charge a high enough premium on their good, it becomes optimal for the firm to produce a more costly higher quality good to maintain their reputation. From my understanding, this is one of the first papers modeling the effect of corporate branding on firm pricing decision. This has broad applicability beyond the IO setting, in my case "firms" would be "artists" deciding whether or not to invest in a costly rehearsal (or some other cost of producing quality art).

2. The authors differentiate their work from its predecessors by arguing that preexisting work relies on external enforcement agencies (like governments) to hold firms accountable to contracts. This paper gives a free market mechanism (branding) for accountability. This only works when consumers have the option to buy from the same company multiple times, so the threat of losing future revenue can serve as sufficient punishment.

3. This paper has no data at all, but does run a simulation of the proposed model under a particular production function assumption, although it's left as an appendix that I haven't researched extensively. It is not the foccus of the paper.

4. In terms of methodology, I'll talk through briefly how the model works. In each period, a firm can choose to produce and sell a high quality good or a low quality good. The high quality good costs more to produce. Consumers cannot distinguish ex ante the quality of the good that the firm is selling, so the firm may have an incentive to masquerade a low quality good as a low quality. However, once  the product is in the hands of consumers, they can observe the quality of the good and update their reputation about the company. All consumers share information instantly, (so effectively there's only one consumer). Firm reputation is assumed to be binary in the eyes of the consumers. That is, consumers start fully trusting a company until they receive one deception, and upon receiving a deceitful product they are only willing to pay for the low quality good at the lower price. It is important to stress that the relationship between reputation and consumer decisions is imposed by the authors and not endogenous.

5. The main results of the paper are that given suffcient market conditions, a high-quality, high-reputation firm can last over multiple periods. These results depend on two parameters, the discount factor and the premium that a reputable firm can charge for a high quality good. If the firm has a sufficiently low discount factor (high present bias), they don't see future revenues as something worth investing in and will spend their reputation on deceiving consumers immediately. The other factor is the premium for high quality goods. If the firm receives little benefit from the high quality good, they would rather take a the supernormal profits from deception in one period and subsequently sell in the low-quality, low-reputation market. These results are consistent with basic intuition, but you have to wonder of much of this comes from the simplistic consumer behavior assumption. The other important point assumption that this paper makes, that I will relax in my analysis is the deterministic production function. In my analysis, the firm (artist) might try hard to produce high quality work, but the hands of fate might nullify those efforts.

6. I think I have made my critique clear that the consumer behavior pattern is simplistic, but that's not really a negative for this paper. It serves as a **solveable** jumping off point for further research. In addition to adding stochastic production technology and more nuanced consumer behavior, I'm interested in exploring the model outside of the perfect competition framework that this paper imposes.

### Premiums for High Quality Products as Returns to Reputations

`r capture.output(print(refs[4]))`

1. This paper is actually quite similar in topic to @kleinRoleMarketForces1981. This paper explores how firms invest in branding over time, however, this paper somewhat relaxes the stringent assumptions on the evolution of consumer behavior. This paper also allows for a more dynamic market with new entrants and more firm pricing flexibility. It seems to build on the model proposed by @kleinRoleMarketForces1981 and gives it wider applicability. 

2. This paper positions itself as an expansion on @kleinRoleMarketForces1981, relaxing some of the assumptions that it makes and giving a more complete picture of the market. The authors stress the importance of this paper existing in a market with free entry where reputation is earned and not innate.

3. This paper has no data and no simulation; it's a theory paper!

4. In terms of theoretical methodology, I will touch on how this model differs from @kleinRoleMarketForces1981. The first major difference to was that quality is no longer discrete, the firm chooses a quality from a continuum and there is a cost function that is increasing in quality. This immediately adds complexity to the long term decisions of the firm because they can now "milk" their reputation down slowly instead of losing all their reputation in one go. The next key difference is the existence is the existence of an equation of motion (the reputation update function). The authors initially use $R_t=q_{t-1}$, reputation is last period's quality, but explore a more general reputation development function that might have more complex intertemporal relations. Consumers are heterogeneous in preferences but not in beliefs about reputation. That is, some might be willing to pay for high quality while others won't, but everyone agrees whether or not a firm is deviant. The other main feature of this paper I would like to discuss is its approach to solving the model. The model assumes that the market is in equilibrium and uses that to deduce some key characteristics that the solution must have. One such example is their "no milking" condition [@shapiroPremiumsHighQuality1983, p. 666]  which says that a situation cannot be an equilibrium if a company has incentive so lower its quality over time and "milk" their reputation. This same equilibrium thinking applied for market clearance another. Another interesting and useful feature of this model is its endogenous new-entrant reputation value. However, in equilibrium, the authors insist that there should be no incentive for new firms to enter (else new entrants would push the market out of equilibrium).

5. The results here are similar to @kleinRoleMarketForces1981 in that they show that even under perfect competition, reputations can be manitained so long as there is a sufficient price incentive to do so. In this paper, that manifests more as a significant percentage of the population getting high utility from high quality. I don't fully understand the justification of this, but the author states that "... a good reputation need not confer market power on its owner. Indeed, firms face perfectly elastic demand curves in the model presented above." [@shapiroPremiumsHighQuality1983 p. 678].

6. Appealing to an equilibrium solution, makes finding a closed form much more attainable, though a natural extension of this paper would be to explore not just the equilibrium, but the path thereto. I think that my interests really like along the path to equilibrium, namely how a new artist entering an unsettled market deals with building reputation. 

### Job Market Signaling

`r capture.output(print(refs[5]))`

1. This paper differs from the other sources in my annotated bibliography because @spenceJobMarketSignaling1973 lives in the labor economics literature and not the marketing literature. @spenceJobMarketSignaling1973 is the pioneering text on how signals of aptitude inform firm hiring decisions. The paper argues that even if a signal gives no information about marginal product, it still can be used in hiring decisions (essentially discrimination can exist without any differences in aptitude).

2. It's actually quite hard to explain how Spence contextualizes his work in relation to others because at least according to him he is really the first formalization of signaling to economics. The [20614 people who have cited his paper](https://scholar.google.com/scholar?cites=13378565684387325505&as_sdt=5,39&sciodt=0,39&hl=en) seem to agree that his contribution was groundbreaking.

3. This paper has no data. It literally has no citations! It's a pure theory paper!

4. While I don't envision myself using a model similar to this, I will explain how the model is constructed and why it differs from the model I intend to use. Spence begins by assuming that there are two types of workers, low marginal product workers and high $MP$ workers. If there were no signaling, the firm would have no other ways to distinguish high from low productivity workers. Spence further assumes that for the high marginal product workers, educational attainment level $y$ is less costly ($y/2$) than the same level of education for a low $MP$ worker, $y$. In this way educational attainment serves as a signal of marginal product. Given that education level $y$ is the only observable trait on the firm's end, they must decide their wage function $W(y)$, only on the education level they can see. The crux of this paper comes in finding an equilibrium of beliefs and behaviors. First, the firm has a belief function. They are thinking, if I observe signal $y$, then I believe that the applicant is high type with one probability and low type with the other. According to these beliefs, the firm makes a $W(y)$ to maximize its expected returns $MP-W(y)$. This choice of $W(y)$ induces the applicant pool to obtain a certain level of education. Upon hiring according to induced $y$s, the observes the distribution of $y$s vs marginal product, and updates its beliefs. This cycle continues until an equilibrium is reached where beliefs are self-confirming. To find this equilibrium Spence takes a "guess" [@spenceJobMarketSignaling1973, p. 362] and his guess happens to create a set of self-confirming beliefs. Less importantly to my analysis, Spence then discusses how an information-less but observable signal can sustain an equilibrium where those with different signals are treated differently (eg different races). I will not be pulling from this model because I am interested in the development of reputations. I initially thought that sending signals would be a good way to model how reputation is built, but in seeing the brandnig literature, using intertemporal delivered product as the primary vehicle for reputation building as a simpler, more direct approach. Further, Spences "guess" model gives me little insight into how to extend his analysis into more complicated situations.

5. The main results of this paper are that signals can accurately differentiate applicants in equilibrium. In the case of education, the signals give the employer meaningful insight, but Spence also argues that signals can produce potentially suboptimal results.

6. This paper will turn 50 next year, so critiquing such a innovative and now quite old paper seems a little misguided. I think the main thing that I would want to explore is how one can deductively find equilibria to the wage-setting signal-sending equilibrium (instead of guess and check). This paper served to close off a channel of research to me, and that has been helpful in reorienting my thoughts to the marketing literature!



### Handbook of the Economics of Marketing

`r capture.output(print(refs[1]))`

I know that this is not a journal article published in a leading journal, but it has been too important to my research process to exclude.

1. This textbook chapter provides theoretical and empirical techniques to model the effect of corporate branding (or more generally reputation) on producer and consumer decisions. In addition, this resource provides basic models as a jumping off point for more complex models. Finally this chapter is an excellent resource to find the semnial texts in the marketing literature.

2. The work in this chapter rightfully positions itself as an accessible entry point into the branding literature. 

3. This source points to some papers that do empirics, but I must admit that I did not really look into them at this stage. 

4. Instead of providing one distinct model, it gives an overview of how branding can be approached. They give cases on the consumer side (eg how does branding affect my purchase decisions) as well as cases on the producer side (eg should my company make costly higher quality product to sustain a reputation). I learned about reputation through their simplified version of @kleinRoleMarketForces1981 which functions in a monopolist environment which allowed me to understand how each of the attributes of the model function. 

5. This source doesn't have results per se, it more focuses as an overview of which results can be attained under which modeling decisions. The main takeaway is that branding is an important asset that firms should invest in like any other asset!

6. I have no real criticism for this source. It has been invaluable in giving me the lay of the land for the marketing literature and pointing towards source that provide simple but robust models of how reputations can be built and maintained. I include this source in my annotated bibliography because without it I would not have found many of these other sources, and for that reason excluding it would seem disingenuous. 
\newpage

### Bibliography

---
nocite: '@*'
---
