---
title: "Money For Nothing, Clicks for Free (Haha, so funny and it's also been done before)"
author: "Aaron Graybill"
date: "10/7/2021"
output:
  pdf_document: default
  html_document: default
biblio-style: apalike
csl: ../apa.csl
bibliography: Draft3.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
The advent of social media and streaming services like Spotify, Youtube, and Instagram have given artists of all kinds unprecendented ability to connect their work to their audience (SOURCE?). However, the increased supply of artists makes it harder for each to cut through the noise and reach financial freedom from their craft (SOURCE?).

Throughout history, artists have had to earn the accolades of their fan. Yatta yatta, that's still true, but this paper explores how the introduction of internet media changes the economic incentives and decisions of artists.

This paper develops and analyzes a model of how artists build and maintain a reputation. This paper pulls from the cultural economics of [@rosenEconomicsSuperstars1981a] and the branding literature [@kleinRoleMarketForces1981; @shapiroPremiumsHighQuality1983].


## Model

### Overview

I will now outline a model of how artistic reputation develops over time. To do this, I will first examine the consumer's problem in which she decides to consume a quantity of different artists' work taking as given the price and current reputation of the firm. The consumer's consumption choice will specify a demand function relating quantity consumed to price and current reputation. The artist (firm) takes the demand function and their current reputation as given and sets a price of their work which determines present profit and next period's reputation. The artist chooses prices in every period that maximize their discounted lifetime profits.

### The Consumer's Problem

I begin by assuming that there exists a representative consumer who has per-period income $I$. She derives per-period utility according to $U(g,a)$ where $g$ is a numeraire aggregate consumption good, and $a$ is the value of artistic consumption. I assume monotonicity in both goods: $U_g>0$ and $U_a>0$. I further assume that he consumer has decreasing marginal utility from each additional unit of consumption: $U_{gg}<0$ and $U_{aa}<0$. These assumptions are consistent with standard economic assumptions of consumer behavior. Finally, I assume that the consumer's utility is quasilinear such that $U(g,a)=u(g)+v(a)$. I assume that the consumer is only concerned with consumption in each period and does not consider future utilities.

Now I assume that the value of art, $a$, does not come from a single good but from the portfolio of art that the consumer purchases. In fact, I assume that there exists a continuum of partially substitutable artists indexed by $i\in[0,N]$, where $N$ parametrizes the total number of artists. The consumer derives utility from the amount of art she consumes from each seller, denoted $n(i)$ as well as the reputation of the artist, $r(i)$, that she consumes from. Following [@rosenEconomicsSuperstars1981a], I assume that quantity and reputation are strongly substitutable and can be modeled as a single unit $r(i)n(i)$. This assumption is conducive to the now-canonical monopolistic competition model presented in [@dixitMonopolisticCompetitionOptimum1977]. As such I let:
\[
v(a)=\left(\int_{0}^N(r_in_i)^\rho di\right)^\frac{1}{\rho}
\]

We assume that consumers take the price for a certain artist's work as given, but that the price level is determined by the reputation of the artist and the number of units that the artist decides to sell. Denote the number of goods sold by the artist $m(i)$ As such, the price is given by $p(r(i),m(i))$. For the consumer's problem, this is equivalent to $p(i)$.

As such, the consumer's only choice variables are the number of units to consume from each artist, $n(i)$, and the number of non-art goods she consumes $g$. She chooses this bundle to maximize her utility subject to her budget constraint: $g+\int_0^N n(i)p(i)di\leq I$.

If the consumer commits to spending $E_a$ on artistic goods, then the Marshallian demand for units ofany artist $i$ becomes:
\[
n(i)=\left(P\frac{r(i)}{p(r(i))}\right)^\sigma\frac{E_a}{r(i)P}
\]

Where the elasticity of substitution is given by $\sigma=\frac{1}{1-\rho}$, and the aggregate reputation-adjusted price level is $P=\left[\int_0^N\left(\frac{p(r(\omega))}{r(\omega)}\right)^{1-\sigma}d\omega\right]^{\frac{1}{1-\sigma}}$. Since there are a continuum of firms, price changes from a finite or countably infinite number of firms has no affect on the aggregate price level, $P$.

Then the consumer chooses how to allocate their income $I$ towards artistic goods $E_a$ and consumption goods $g$. The consumer's optimal choice of artistic consumption for firm $i$ becomes:
\[
n(i)=\left(P\frac{r(i)}{p(r(i))}\right)^\sigma\frac{I-[v']^{-1}\left(\frac{1}{P}\right)}{r(i)P}
\]

The expression above gives the Marshallian demand for art from artist $i$ in terms of the price that artist $i$ sets and the reputation they have in the current period. The artist will use this demand function when deciding the optimal price level to set.

### The Artist's Problem

We model the artist's problem dynamically. Let the artist have underlying artistic talent $k$ (it can be viewed as a relative of capital). The market is assumed to be monopolistically competitive, so every artist has full control of their price in every period, but price decisions may cause consumers to substitute to other products. The artist takes their current reputation as given. This assumption is used to simplify analysis. Allowing a flexible reputation in the current period obfuscates how reputation evolves by allowing producers to increase there reputation more quickly. As argued above, consumer demand is a function of both price and reputation. However, with the fixed reputation, the artist only has access to a single demand curve in each period. Changes to reputation in future periods shift the artist's available demand curve. This can be represented graphically in the following way.

**HERE IS WHERE I DRAW DEMAND CURVE PICTURE**

The artist's current revenue is the product of the price they set, $p$, and the demand induced by that price choice **$n(i,p,r)$ This is terrible notation, help**. In addition to revenue, the artist's choice of price affects the number of goods they must produce which incurs some cost $C(n(p,r))$. **ADD ASSUMPTIONS ABOUT CONVEXITY IF WE'RE DOING THAT**. The current period's profit is given by $p\cdot n(i,p,r)-C(n(p,r))$.

The artist's problem is not just to maximize current profits, but to maximize the discounted stream of all profits. Unlike traditional growth models, the link tying one period to another is not capital accumulation, but reputation accumulation. I assume that next period's reputation, $r'$, is a function of the current period's reputation, and the number of units sold. Denote this reputation $\mathcal{R}$ such that $r'=\mathcal R(n,r)$. The functional form of $\mathcal R$ is integral to this analysis and multiple specifications will be examined and connected to real world scenarios. 

We can formulate the artist's problem two ways. First, I can think of the artist choosing a $p_t$ and $r_{t+1}$ in every period. I can represent this as:
\[
\max_{p_t,r_t}\left\{\sum_{t=0}^\infty\beta^t\left(p_t\cdot n(i,p_t,r_t)-C(n(p,r_t))\right) \ s.t. \ r_{t+1}=\mathcal R(n(i,p_t,r_t),r_t)\right\}
\]


Alternately, I can define the firm's problem recursively, the agent's maximal discounted lifetime profit is their profits in this period plus their discounted maximal lifetime  from next period onward. The state variable that links one period to the next is their reputation, $r$. As such The Bellman equation is the function $V(r)$ satisfying

\[
V(r)=\max_{m}\left\{p(r)m-C(m)+\beta V(r') \ \ s.t. \ \ r'=\mathcal{R}\left(m,r\right)\right\}
\]

## Exploration of First Order Conditions

I will extensively use the fact that $-\sigma n(\cdot)= p n_p(\cdot)$ (this is a biproduct of CES).

Using the every-period summation model, the first order conditions are that:

\begin{align*}
\frac{\partial V}{\partial p}&\colon \beta^t\left[n(\cdot)+p\cdot n_p(\cdot)-C'(n)n_p(\cdot)\right]-\lambda \mathcal R_n(\cdot)n_p(\cdot)=0\\
\frac{\partial V}{\partial r_{t+1}}&\colon \lambda = 0\\
\frac{\partial V}{\partial r_{t+1}}&\colon \ r_{t+1}=\mathcal R(n(p_t,r_t),r_t)
\end{align*}


## Market Equilibrium

Any equilibrium requires that I find a $p(r)$ and series of $m$ and $n$ over time such that market's clear ($m=n$)

## Perturbation Exploration (reputational Shocks)



\newpage
## Bibliography


