---
title: "Exposure Doesn't Pay the Bills"
author: "Aaron Graybill"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: 
    number_sections: true
  word_document: default
  html_document: default
biblio-style: apalike
csl: ../apa.csl
bibliography: ../RunningBib.bib
nocite: 
linestretch: 1.5
indent: true
urlcolor: blue
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
- \let\textlozenge\relax
- \usepackage{heuristica}
- \usepackage[heuristica,vvarbb,bigdelims]{newtxmath}
- \usepackage[T1]{fontenc}
- \renewcommand*\oldstylenums[1]{\textosf{#1}}
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F,message=F,warning=F)
```

# The Model

The streaming economy has three primary actors: the end consumer, the streaming platform, and the artist. For the purposes of this analysis, I will assume that the behavior of the consumer and the streaming platform are exogenous. I will limit attention to the artist who must choose a quality and quantity of art to produce. The streaming platform's algorithm is driven by consumer engagement last period. It combines this user engagement with the number of new releases to decide the number of new consumers to show an artist's work to. I will assume that consumers have no ex ante knowledge of an artist and require the algorithm to reveal an artist to them. I will call these algorithmic revelations, impressions. Once a consumer has received an impression, their number of streams will depend on the quality of the art that the artist released in that period. The algorithm observes the streams per impression and uses this to decide how many times to show the artist's work next period.

The artist earns a royalty every time a song is streamed, and the artist tries to maximize this discounted flow of royalties. The trade-off between quantity of releases and the quality of those releases will be central to their maximization problem. Increases to quality ensure that once a consumer receives an artist's work, they will consume that product more. Increasing quality also has the inter-temporal benefit of encouraging next period's algorithm to show the art to more consumers. On the other hand, the artist can increase their quantity at the expense of quality. The algorithm will have more pieces to show to consumers (increasing the probability that a given consumer discovers an artist), but it also leaves audience size more up to the random component of the algorithm.

## Hypotheses

Before describing the model in detail, I will first lay out hypothesized results based on the literature presented above. The first hypothesis pertains to the "long tail" theory described in @aguiarQualityPredictabilityWelfare2018. Following @rosen1981, I will measure the long tail of outcomes by examining the convexity of the expected profit function in an artist's underlying talent. I pose the following:

> *Hypothesis 1: Unpredictability of a streaming platform's content matching algorithm will decrease the convexity of profits in talent.*

The second hypothesis relates to audience development. Similar to the work of @benderAttractingArtistsMusic2021, I will examine how the choices of established artists differ from artists with smaller starting audiences.

> *Hypothesis 2: Artists with smaller initial audiences will be more likely to choose a low-quality, high-quantity strategy relative to established artists.*

The final hypothesis pertains to how the previous hypothesis is affected by time. The quality-quantity trade-off becomes less clear cut when quality informs next period's audience. I propose:

> *Hypothesis 3: Artists will prioritize quality more in a multi-period setting than they will in a one-period environment.*

## Consumer Behavior

I assume there is an infinitely large market of consumers with identical preferences on a streaming platform. This assumption does not fully depict the consumer-base of a streaming platform. However, for an emerging artist in an established genre, this assumption is more realistic. Ex ante, consumers have no knowledge of a given artist and require the algorithm to reveal an artist to them. Upon receiving an impression of an artist, the consumer gains knowledge of all of an artist's work from that period, not just the piece they were exposed to. I will assume that after an impression a consumer will stream the artist's work $n(z)$ times, where $z$ is the quality of the art. I will assume that $n_z>0$ and $n_{zz}<0$, so increases to quality always increase demand, but at a lessening rate. A notable assumption in the above modelling decision is that the quantity of releases has no influence on the amount of streams by a given consumer. Consumers see the quality and might choose to stream one song all $n$ times, or they might spread their consumption across multiple pieces of art.

## Artist Behavior

The artist's problem is to maximize the royalties they receive from their audience streaming their music. In particular, I will assume that each stream earns the artist an amount $r$, so the total revenue in each period is the total number of streams time $r$. The artist chooses to produce $m$ pieces each of which at the same quality $z$. I will assume that the artist's combination of $m$ and $z$ also incur a cost $C(m,z;\kappa)$ where $\kappa$ is the artist's underlying talent that makes production easier. An more typical approach too introducing a talent parameter would be as a positive influence on production, not cost. However, interpreting cost in terms of opportunity cost allows us to include talent not as reducing monetary cost but the non-pecuniary cost of producing an additional unit of art. I will impose some standard assumptions on $C$. Namely, I will assume $C_m>0,C_z>0,C_{mm}>0,C_{zz}>0,C_{z\kappa}<0,C_{m\kappa}<0$. The assumptions say that increases to quality or quantity also increase cost, and additional units of quantity of quality are more costly than the previous. The cross partial derivatives say that increasing talent decrease the marginal cost in each of the inputs. In order for $\kappa$ to be meaningful as a talent parameter, we should require that at every input, an additional unit of talent makes the next unit of production less costly. I will further assume $C_\kappa<0$ and $C_{\kappa\kappa}>0$, so increases to underlying talent lower costs, but additional increases to talent are less and less impactful.

## Audience Evolution and Algorithmic Behavior

There are three drivers of audience evolution: last period's audience, the new audience algorithm, and the unforecastable random noise present in the algorithm. I will assume that every period, a fraction $\delta$ of the audience "forgets" about an artist and needs reimpression in order to consume an artist's work again. As such, the share of last period's audience that endures is $(1-\delta)$. The other two components are related to the algorithm. I assume that the streaming platform's algorithm governs the number of new impressions for each song released by an artist. For the algorithm to be a meaningful tool, it should not be entirely random. It should some measure of engagement to dictate how many impressions in the next period. For the purposes of this model, the algorithm will use last period's number of streams per audience member as the measure of engagement. By construction, at time $t$, the algorithm will use $n(z_{t-1})$, so the algorithm is indirectly incorporating quality.

There are multiple ways to interpret the uncertainty in the algorithm. One such way is to interpret a streaming platform's algorithm as an imperfect instrument that measures talent. An alternate way to interpret algorithmic uncertainty is in the context of producer uncertainty. In this case, the artist understands the average effects of the algorithm, but the streaming platform intentionally or inadvertently obfuscates exactly how the algorithm behaves so there is always some artist uncertainty about the true number of impressions in the next period. One concern when modeling an uncertain algorithm is that artist with higher talent may be favored by the random component of the algorithm. However, most artists, at least for professional content creators, can observe any information in the algorithm that might benefit them when making their product. By definition, the most algorithmically favored products are shown the most. As such, artists have ample opportunity to analyze which components of successful and any useful information can be quickly arbitraged out by observant content creators. Further analyses could explore this relationship in more detail, but this model will assume that talent and algorithmic uncertainty are independen.t

With the aforementioned assumption, I construct the algorithm as follows. First denote the impression algorithm for an artist's $i$th art piece in period $t$ as $I(n_{t-1})+\varepsilon_{it}$ where $\varepsilon_{it}$ is a mean zero independent identically distributed random variable. Interpreting the algorithm as a useful, if imperfect, measure of quality, I will assume that $I_n>0$. So increases to engagement mean more exposures next period.

For each art piece that an artist produces in the present period, they must submit this work through the algorithm which is subject to random noise. The artists total number of impressions from the audience is then given by $mI(n_{t-1})+\sum_{i=1}^m \varepsilon_{it}$. As such, the expected number of impressions is simply $mI(n_{t-1})$ with variance $m\textrm{Var}(\varepsilon)$. Increasing the number of releases increases the expected audience, but equally increases the variance of outcomes. Putting all of these pieces together, the equation of motion for audience size at time $t$, $A_t$, is given by:

```{=tex}
\begin{equation} \label{eq:eqn_of_motion}
A_t=(1-\delta)A_{t-1}+mI(n_{t-1})+\sum_{i=1}^m\varepsilon_{it}
\end{equation}
```
## The Artist's One-Period Maximization Problem

We can assemble the above pieces into the respective one-period revenue maximization problem. The timing of the model is as follows, the artist chooses $m$ and $z$, then the random variables in the algorithm are realized, then consumers stream the artist work according to $n(z)$. As such, we can express the artist's problem as:

```{=tex}
\begin{equation} \label{eq:one_period_general}
V(m,z)=\max_{m,z}\left\{E\left[rA_tn(z)-C(m,z;\kappa)\right]  \textrm{s.t.}A_t=(1-\delta)A_{t-1}+mI(n_{t-1})+\sum_{i=1}^m\varepsilon_{it}\right\}
\end{equation}
```
Substituting in with $A_t$ allows us to solve this problem as an unconstrained maximization problem with the following first order conditions:

```{=tex}
\begin{equation} \label{eq:general_focs}
\begin{split}
\frac{\partial V}{\partial z}&\colon r\left[(1-\delta)A_{t-1}+mI(n_{t-1})\right]mn'(z)-C_z(m,z;\kappa)=0 \\
\frac{\partial V}{\partial m}&\colon r I(n_{t-1})n(z)-C_m(m,z;\kappa)=0
\end{split}
\end{equation}
```
I will now use the implicit function theorem to interpret some comparative statics in terms of the parameters of the model. I summarize the results below

|                     | $\partial m$ | $\partial z$ |
|---------------------|:------------:|:------------:|
| $/\partial r$       | $\downarrow$ | $\downarrow$ |
| $/\partial \delta$  |     $0$      |  $\uparrow$  |
| $/\partial A_{t-1}$ |     $0$      | $\downarrow$ |
| $/\partial n_{t-1}$ | $\downarrow$ | $\downarrow$ |
| $/\partial \kappa$  | $\downarrow$ | $\downarrow$ |

Since $z$ does not affect the future engagement measures (because I only consider one period), the artist will try to substitute away from using $z$ in production because it is more costly. As such, when the royalty rate increases, the artist will be able to recoup the same amount of revenue selling fewer units, so they will chose to lower their $z$ due to it's increasing costliness.

We have a similar result for changes to the quantity produced. Again, producing more quantity incurs costs that the artist substitutes away from when given more slack by the other parameters. Interestingly, the previous period's audience makes no impact on the artist's choice to produce a greater quantity. This comes from the fact that prior audience is sunk in $m$. Since $m$ can only influence the number of new listeners, the artist need not consider how much of the previous audience they've retained.

## One Period-Binary Choice Example

To fix ideas, I will now explore the case in which the artist can only choose from one of two options. In order to collapse the problem to a binary choice set, instead of using a cost function, I will use a budget constraint, $C(m,z)=Y$ which implicitly defines $z$ in terms of $m$. As such, let's consider the case where the artist is choosing to produce either $1$ or $2$ products. If the artist chooses $m=1$, they can produce one higher quality good at quality $\overline{z}$. In the other case, the artist can produce $2$ goods, each at quality $\underline{z}$. The artist will then choose:

```{=tex}
\begin{equation} \label{eq:binary_choice}
\max\left\{r\left((1-\delta)A_{t-1}+I(n_{t-1})\right)n(\overline{z}),r\left((1-\delta)A_{t-1}+2I(n_{t-1})\right)n(\underline{z}) \right\}
\end{equation}
```
The artist's optimal production choice can be summarized as

```{=tex}
\begin{equation} \label{eq:one_period_behavior}
\begin{cases}
\underline{z} &  n(\overline z) < \left(1+\frac{I_0}{I_0+(1-\delta)A_0}\right)n(\underline z)\\
\textrm{Either} & n(\overline z) = \left(1+\frac{I_0}{I_0+(1-\delta)A_0}\right)n(\underline z) \\
\overline{z}, &  n(\overline z) > \left(1+\frac{I_0}{I_0+(1-\delta)A_0}\right)n(\underline z)
\end{cases}
\end{equation}
```
By monotonicity of demand $n(\overline{z})/n(\underline{z})>1$, so we can think of $\frac{I_0}{I_0+(1-\delta)A_0}$ as the minimal premium for which the artist will produce the high quality option. Begin by noting that the denominator in the above expression is the expected audience size when the artist chooses the high quality option. As such, we can interpret the premium as the percent of expected audience that is earned by the algorithm. Holding other factors equal, an artist with a larger initial audience is more likely to have a smaller premium to induce high quality production relative to a new artist where most of their audience is new. Therefore, established artists are more likely to produce high quality content. In contrast, new artists are likely to produce a greater number of lower-quality art and rely on the algorithm to get their art into the hands of new consumers.

## Two Period Binary Choice

I now explore the case where the artist has the same options as before, one or two products at quality $\overline z$ and $\underline z$ respectively. However, in this case, I examine the artist's behavior over two periods. In this case, their choice of $z$ in the first period influences the number over impressions that the algorithm produces next period. I will now introduce some new notation. Let $\overline {I}$ be the impressions awarded to the artist when their choice of quality $\overline z$ induces consumption $n(\overline z)$. Define $\underline I$ analogously. We proceed using backwards induction. I have already fully characterized behavior in the final period, so we can take optimal second-period behavior as given when characterizing optimal artist behavior.

Artist has four options, either quality in either period.

## Next Steps

I don't have the time to juggle all of the inequalities of that two period model right now , but I will briefly summarize my next steps.

1.  Solve that two period model and see if new artists are more incentivized to invest in quality
2.  Given optimal two-period play, how large of a shock is required in order to make an artist change their strategy in the second period. Conducting this analysis is quite simple once I've found optimal play because we've already characterized final-period optimal play, so we can see how artist set them self up for period two, and then look at how far away the inequality bounds are from their chosen set up, and that gives how sensitive the artist is to a shock.
3.  In the one period model, examine how an initial distribution of talent is transformed when considering optimal play. I haven't totally figured out the best way to explore this because in the binary-choice case, talent doesn't enter directly, so I'd have to think the non-binary functions $\underline{z}(\kappa)$ and $\overline{z}(\kappa)$ but that doesn't feel right. If I try to use the general equations, I don't know how to convert the FOCs into distributional analysis
4.  This I have no idea how to implement, but I'm really interested in the conditions under which the market naturally brings talented to the top. For example, does a sufficiently large shock guarantee you're popular forever, or do the effects of shocks eventually die out because you can't maintain the level of quality needed to retain such a large audience.

\newpage

# References {.unnumbered}
